-- Additive tenant-bound foreign keys keep existing single-column keys for compatibility
-- while making the database reject cross-tenant relationships. Pair-unique constraints
-- are required by PostgreSQL for composite foreign-key targets.

-- Composite foreign-key targets.
ALTER TABLE public.approval_instances ADD CONSTRAINT uq_tenant_approval_instances_id_549b2532 UNIQUE (tenant_id, id);
ALTER TABLE public.approval_steps ADD CONSTRAINT uq_tenant_approval_steps_id_4ea8a844 UNIQUE (tenant_id, id);
ALTER TABLE public.approval_workflow_versions ADD CONSTRAINT uq_tenant_approval_workflow_versions_id_2aee96f1 UNIQUE (tenant_id, id);
ALTER TABLE public.approval_workflows ADD CONSTRAINT uq_tenant_approval_workflows_id_527755eb UNIQUE (tenant_id, id);
ALTER TABLE public.audit_logs ADD CONSTRAINT uq_tenant_audit_logs_id_409b51e1 UNIQUE (tenant_id, id);
ALTER TABLE public.background_jobs ADD CONSTRAINT uq_tenant_background_jobs_id_1ef6da73 UNIQUE (tenant_id, id);
ALTER TABLE public.companies ADD CONSTRAINT uq_tenant_companies_id_14651675 UNIQUE (tenant_id, id);
ALTER TABLE public.contract_items ADD CONSTRAINT uq_tenant_contract_items_id_23779df9 UNIQUE (tenant_id, id);
ALTER TABLE public.contracts ADD CONSTRAINT uq_tenant_contracts_id_e9839443 UNIQUE (tenant_id, id);
ALTER TABLE public.customers ADD CONSTRAINT uq_tenant_customers_id_4b6f7d34 UNIQUE (tenant_id, id);
ALTER TABLE public.files ADD CONSTRAINT uq_tenant_files_id_45b96339 UNIQUE (tenant_id, id);
ALTER TABLE public.import_jobs ADD CONSTRAINT uq_tenant_import_jobs_id_072974ec UNIQUE (tenant_id, id);
ALTER TABLE public.invoice_batches ADD CONSTRAINT uq_tenant_invoice_batches_id_4b5ed7fb UNIQUE (tenant_id, id);
ALTER TABLE public.invoice_preview_adjustments ADD CONSTRAINT uq_tenant_invoice_preview_adjustments_id_a9fa8e8b UNIQUE (tenant_id, id);
ALTER TABLE public.invoice_preview_items ADD CONSTRAINT uq_tenant_invoice_preview_items_id_04abeee7 UNIQUE (tenant_id, id);
ALTER TABLE public.invoice_previews ADD CONSTRAINT uq_tenant_invoice_previews_id_b4120d62 UNIQUE (tenant_id, id);
ALTER TABLE public.invoice_profiles ADD CONSTRAINT uq_tenant_invoice_profiles_id_08490f3c UNIQUE (tenant_id, id);
ALTER TABLE public.invoice_template_versions ADD CONSTRAINT uq_tenant_invoice_template_versions_id_3401e29e UNIQUE (tenant_id, id);
ALTER TABLE public.invoice_templates ADD CONSTRAINT uq_tenant_invoice_templates_id_41ae3aa6 UNIQUE (tenant_id, id);
ALTER TABLE public.invoices ADD CONSTRAINT uq_tenant_invoices_id_56deca22 UNIQUE (tenant_id, id);
ALTER TABLE public.librenms_bill_mappings ADD CONSTRAINT uq_tenant_librenms_bill_mappings_id_d1c254d1 UNIQUE (tenant_id, id);
ALTER TABLE public.librenms_instances ADD CONSTRAINT uq_tenant_librenms_instances_id_1023db63 UNIQUE (tenant_id, id);
ALTER TABLE public.notification_templates ADD CONSTRAINT uq_tenant_notification_templates_id_c54c5f77 UNIQUE (tenant_id, id);
ALTER TABLE public.payments ADD CONSTRAINT uq_tenant_payments_id_84d5eaf7 UNIQUE (tenant_id, id);
ALTER TABLE public.pricing_rules ADD CONSTRAINT uq_tenant_pricing_rules_id_bd1e2288 UNIQUE (tenant_id, id);
ALTER TABLE public.products ADD CONSTRAINT uq_tenant_products_id_86024cad UNIQUE (tenant_id, id);
ALTER TABLE public.roles ADD CONSTRAINT uq_tenant_roles_id_4295e806 UNIQUE (tenant_id, id);
ALTER TABLE public.service_groups ADD CONSTRAINT uq_tenant_service_groups_id_83be7301 UNIQUE (tenant_id, id);
ALTER TABLE public.services ADD CONSTRAINT uq_tenant_services_id_10cd395c UNIQUE (tenant_id, id);
ALTER TABLE public.usage_snapshots ADD CONSTRAINT uq_tenant_usage_snapshots_id_0d7cba10 UNIQUE (tenant_id, id);

-- New writes are checked immediately; validation then scans all pre-existing rows.
ALTER TABLE public.approval_actions ADD CONSTRAINT fk_tenant_approval_actions_actor_id_247cb391 FOREIGN KEY (tenant_id, actor_id) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.approval_actions ADD CONSTRAINT fk_tenant_approval_actions_approval_instance_id_d3d74081 FOREIGN KEY (tenant_id, approval_instance_id) REFERENCES public.approval_instances (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE public.approval_actions ADD CONSTRAINT fk_tenant_approval_actions_approval_step_id_af3f2ef9 FOREIGN KEY (tenant_id, approval_step_id) REFERENCES public.approval_steps (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.approval_instances ADD CONSTRAINT fk_tenant_approval_instances_invoice_preview_id_c67e379f FOREIGN KEY (tenant_id, invoice_preview_id) REFERENCES public.invoice_previews (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE public.approval_instances ADD CONSTRAINT fk_tenant_approval_instances_requested_by_56e54503 FOREIGN KEY (tenant_id, requested_by) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.approval_instances ADD CONSTRAINT fk_tenant_approval_instances_workflow_version_id_b766650d FOREIGN KEY (tenant_id, workflow_version_id) REFERENCES public.approval_workflow_versions (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.approval_steps ADD CONSTRAINT fk_tenant_approval_steps_workflow_version_id_cf81c29e FOREIGN KEY (tenant_id, workflow_version_id) REFERENCES public.approval_workflow_versions (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE public.approval_workflow_versions ADD CONSTRAINT fk_tenant_approval_workflow_versions_workflow_id_0312ce11 FOREIGN KEY (tenant_id, workflow_id) REFERENCES public.approval_workflows (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.approval_workflows ADD CONSTRAINT fk_tenant_approval_workflows_current_version_id_e2aac714 FOREIGN KEY (tenant_id, current_version_id) REFERENCES public.approval_workflow_versions (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.audit_chain_heads ADD CONSTRAINT fk_tenant_audit_chain_heads_last_event_id_5c579e7f FOREIGN KEY (tenant_id, last_event_id) REFERENCES public.audit_logs (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.companies ADD CONSTRAINT fk_tenant_companies_customer_id_9e5312ed FOREIGN KEY (tenant_id, customer_id) REFERENCES public.customers (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.contract_files ADD CONSTRAINT fk_tenant_contract_files_contract_id_3d7ffacf FOREIGN KEY (tenant_id, contract_id) REFERENCES public.contracts (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.contract_files ADD CONSTRAINT fk_tenant_contract_files_file_id_7cacf98c FOREIGN KEY (tenant_id, file_id) REFERENCES public.files (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.contract_items ADD CONSTRAINT fk_tenant_contract_items_contract_id_ad98988d FOREIGN KEY (tenant_id, contract_id) REFERENCES public.contracts (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.contract_items ADD CONSTRAINT fk_tenant_contract_items_pricing_rule_id_ad53cf11 FOREIGN KEY (tenant_id, pricing_rule_id) REFERENCES public.pricing_rules (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.contract_items ADD CONSTRAINT fk_tenant_contract_items_service_id_1bf23236 FOREIGN KEY (tenant_id, service_id) REFERENCES public.services (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.contracts ADD CONSTRAINT fk_tenant_contracts_company_id_91d4c6d7 FOREIGN KEY (tenant_id, company_id) REFERENCES public.companies (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.contracts ADD CONSTRAINT fk_tenant_contracts_customer_id_1ba6505c FOREIGN KEY (tenant_id, customer_id) REFERENCES public.customers (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.customer_contacts ADD CONSTRAINT fk_tenant_customer_contacts_company_id_983f931e FOREIGN KEY (tenant_id, company_id) REFERENCES public.companies (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.customer_contacts ADD CONSTRAINT fk_tenant_customer_contacts_customer_id_7563f8b9 FOREIGN KEY (tenant_id, customer_id) REFERENCES public.customers (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.customers ADD CONSTRAINT fk_tenant_customers_owner_user_id_f3da1a0a FOREIGN KEY (tenant_id, owner_user_id) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.external_identities ADD CONSTRAINT fk_tenant_external_identities_user_id_57b7f6fe FOREIGN KEY (tenant_id, user_id) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE public.files ADD CONSTRAINT fk_tenant_files_created_by_5c3d5d16 FOREIGN KEY (tenant_id, created_by) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.import_jobs ADD CONSTRAINT fk_tenant_import_jobs_error_file_id_2bee57bb FOREIGN KEY (tenant_id, error_file_id) REFERENCES public.files (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.import_jobs ADD CONSTRAINT fk_tenant_import_jobs_requested_by_025de0b8 FOREIGN KEY (tenant_id, requested_by) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.import_jobs ADD CONSTRAINT fk_tenant_import_jobs_source_file_id_3706261e FOREIGN KEY (tenant_id, source_file_id) REFERENCES public.files (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.import_row_errors ADD CONSTRAINT fk_tenant_import_row_errors_import_job_id_58330d3b FOREIGN KEY (tenant_id, import_job_id) REFERENCES public.import_jobs (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE public.import_staging_rows ADD CONSTRAINT fk_tenant_import_staging_rows_import_job_id_fb9813f4 FOREIGN KEY (tenant_id, import_job_id) REFERENCES public.import_jobs (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE public.invoice_adjustments ADD CONSTRAINT fk_tenant_invoice_adjustments_attachment_file_id_0a9e92ba FOREIGN KEY (tenant_id, attachment_file_id) REFERENCES public.files (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_adjustments ADD CONSTRAINT fk_tenant_invoice_adjustments_invoice_id_d63c840c FOREIGN KEY (tenant_id, invoice_id) REFERENCES public.invoices (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_adjustments ADD CONSTRAINT fk_tenant_invoice_adjustments_source_preview_adjustmen_89088b53 FOREIGN KEY (tenant_id, source_preview_adjustment_id) REFERENCES public.invoice_preview_adjustments (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_batches ADD CONSTRAINT fk_tenant_invoice_batches_requested_by_034ef5da FOREIGN KEY (tenant_id, requested_by) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_files ADD CONSTRAINT fk_tenant_invoice_files_file_id_338c21b8 FOREIGN KEY (tenant_id, file_id) REFERENCES public.files (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_files ADD CONSTRAINT fk_tenant_invoice_files_invoice_id_2aacc0d6 FOREIGN KEY (tenant_id, invoice_id) REFERENCES public.invoices (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_files ADD CONSTRAINT fk_tenant_invoice_files_template_version_id_a48b662c FOREIGN KEY (tenant_id, template_version_id) REFERENCES public.invoice_template_versions (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_items ADD CONSTRAINT fk_tenant_invoice_items_contract_item_id_9a22d010 FOREIGN KEY (tenant_id, contract_item_id) REFERENCES public.contract_items (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_items ADD CONSTRAINT fk_tenant_invoice_items_invoice_id_277b6765 FOREIGN KEY (tenant_id, invoice_id) REFERENCES public.invoices (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_items ADD CONSTRAINT fk_tenant_invoice_items_pricing_rule_version_id_8f8b4fc5 FOREIGN KEY (tenant_id, pricing_rule_version_id) REFERENCES public.pricing_rule_versions (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_items ADD CONSTRAINT fk_tenant_invoice_items_service_id_8f2ee3f4 FOREIGN KEY (tenant_id, service_id) REFERENCES public.services (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_items ADD CONSTRAINT fk_tenant_invoice_items_source_preview_item_id_fb1c78e0 FOREIGN KEY (tenant_id, source_preview_item_id) REFERENCES public.invoice_preview_items (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_items ADD CONSTRAINT fk_tenant_invoice_items_usage_snapshot_id_76f9df7b FOREIGN KEY (tenant_id, usage_snapshot_id) REFERENCES public.usage_snapshots (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_preview_adjustments ADD CONSTRAINT fk_tenant_invoice_preview_adjustments_approved_by_b43bbb20 FOREIGN KEY (tenant_id, approved_by) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_preview_adjustments ADD CONSTRAINT fk_tenant_invoice_preview_adjustments_attachment_file__611d244c FOREIGN KEY (tenant_id, attachment_file_id) REFERENCES public.files (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_preview_adjustments ADD CONSTRAINT fk_tenant_invoice_preview_adjustments_created_by_93dd0d68 FOREIGN KEY (tenant_id, created_by) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_preview_adjustments ADD CONSTRAINT fk_tenant_invoice_preview_adjustments_invoice_preview__73a94f3f FOREIGN KEY (tenant_id, invoice_preview_id) REFERENCES public.invoice_previews (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE public.invoice_preview_exclusions ADD CONSTRAINT fk_tenant_invoice_preview_exclusions_created_by_da127772 FOREIGN KEY (tenant_id, created_by) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_preview_exclusions ADD CONSTRAINT fk_tenant_invoice_preview_exclusions_invoice_preview_i_20199df2 FOREIGN KEY (tenant_id, invoice_preview_id) REFERENCES public.invoice_previews (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE public.invoice_preview_exclusions ADD CONSTRAINT fk_tenant_invoice_preview_exclusions_invoice_preview_i_7771e7a1 FOREIGN KEY (tenant_id, invoice_preview_item_id) REFERENCES public.invoice_preview_items (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE public.invoice_preview_items ADD CONSTRAINT fk_tenant_invoice_preview_items_contract_item_id_2808cd28 FOREIGN KEY (tenant_id, contract_item_id) REFERENCES public.contract_items (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_preview_items ADD CONSTRAINT fk_tenant_invoice_preview_items_invoice_preview_id_7006776e FOREIGN KEY (tenant_id, invoice_preview_id) REFERENCES public.invoice_previews (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE public.invoice_preview_items ADD CONSTRAINT fk_tenant_invoice_preview_items_pricing_rule_version_i_1bbddf75 FOREIGN KEY (tenant_id, pricing_rule_version_id) REFERENCES public.pricing_rule_versions (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_preview_items ADD CONSTRAINT fk_tenant_invoice_preview_items_service_id_3ad55b36 FOREIGN KEY (tenant_id, service_id) REFERENCES public.services (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_preview_items ADD CONSTRAINT fk_tenant_invoice_preview_items_usage_snapshot_id_2af767d8 FOREIGN KEY (tenant_id, usage_snapshot_id) REFERENCES public.usage_snapshots (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_previews ADD CONSTRAINT fk_tenant_invoice_previews_approval_workflow_version_i_1262b32d FOREIGN KEY (tenant_id, approval_workflow_version_id) REFERENCES public.approval_workflow_versions (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_previews ADD CONSTRAINT fk_tenant_invoice_previews_company_id_58aa4e25 FOREIGN KEY (tenant_id, company_id) REFERENCES public.companies (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_previews ADD CONSTRAINT fk_tenant_invoice_previews_created_by_7815633d FOREIGN KEY (tenant_id, created_by) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_previews ADD CONSTRAINT fk_tenant_invoice_previews_customer_id_26a2e87d FOREIGN KEY (tenant_id, customer_id) REFERENCES public.customers (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_previews ADD CONSTRAINT fk_tenant_invoice_previews_invoice_batch_id_81c7dec3 FOREIGN KEY (tenant_id, invoice_batch_id) REFERENCES public.invoice_batches (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_previews ADD CONSTRAINT fk_tenant_invoice_previews_invoice_profile_id_472cbd97 FOREIGN KEY (tenant_id, invoice_profile_id) REFERENCES public.invoice_profiles (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_previews ADD CONSTRAINT fk_tenant_invoice_previews_origin_invoice_id_f30e6c82 FOREIGN KEY (tenant_id, origin_invoice_id) REFERENCES public.invoices (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_previews ADD CONSTRAINT fk_tenant_invoice_previews_template_id_832a142b FOREIGN KEY (tenant_id, template_id) REFERENCES public.invoice_templates (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_previews ADD CONSTRAINT fk_tenant_invoice_previews_template_version_id_6dfb617a FOREIGN KEY (tenant_id, template_version_id) REFERENCES public.invoice_template_versions (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_profile_assignments ADD CONSTRAINT fk_tenant_invoice_profile_assignments_contract_item_id_e9d3fed3 FOREIGN KEY (tenant_id, contract_item_id) REFERENCES public.contract_items (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_profile_assignments ADD CONSTRAINT fk_tenant_invoice_profile_assignments_created_by_a265c49b FOREIGN KEY (tenant_id, created_by) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_profile_assignments ADD CONSTRAINT fk_tenant_invoice_profile_assignments_invoice_profile__d774c0cc FOREIGN KEY (tenant_id, invoice_profile_id) REFERENCES public.invoice_profiles (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE public.invoice_profiles ADD CONSTRAINT fk_tenant_invoice_profiles_approval_workflow_id_a785c673 FOREIGN KEY (tenant_id, approval_workflow_id) REFERENCES public.approval_workflows (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_profiles ADD CONSTRAINT fk_tenant_invoice_profiles_company_id_1664b69e FOREIGN KEY (tenant_id, company_id) REFERENCES public.companies (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_profiles ADD CONSTRAINT fk_tenant_invoice_profiles_customer_id_1e6e0076 FOREIGN KEY (tenant_id, customer_id) REFERENCES public.customers (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_profiles ADD CONSTRAINT fk_tenant_invoice_profiles_template_id_65d1e301 FOREIGN KEY (tenant_id, template_id) REFERENCES public.invoice_templates (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_relations ADD CONSTRAINT fk_tenant_invoice_relations_created_by_fed95abb FOREIGN KEY (tenant_id, created_by) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_relations ADD CONSTRAINT fk_tenant_invoice_relations_source_invoice_id_ac9fcb77 FOREIGN KEY (tenant_id, source_invoice_id) REFERENCES public.invoices (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_relations ADD CONSTRAINT fk_tenant_invoice_relations_target_invoice_id_499eccc5 FOREIGN KEY (tenant_id, target_invoice_id) REFERENCES public.invoices (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_template_assets ADD CONSTRAINT fk_tenant_invoice_template_assets_file_id_f35d954a FOREIGN KEY (tenant_id, file_id) REFERENCES public.files (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_template_assets ADD CONSTRAINT fk_tenant_invoice_template_assets_template_version_id_0699ef21 FOREIGN KEY (tenant_id, template_version_id) REFERENCES public.invoice_template_versions (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE public.invoice_template_versions ADD CONSTRAINT fk_tenant_invoice_template_versions_created_by_308fd4fb FOREIGN KEY (tenant_id, created_by) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_template_versions ADD CONSTRAINT fk_tenant_invoice_template_versions_template_id_b3ca52de FOREIGN KEY (tenant_id, template_id) REFERENCES public.invoice_templates (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_templates ADD CONSTRAINT fk_tenant_invoice_templates_created_by_4fc9627c FOREIGN KEY (tenant_id, created_by) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoice_templates ADD CONSTRAINT fk_tenant_invoice_templates_current_version_id_1055498f FOREIGN KEY (tenant_id, current_version_id) REFERENCES public.invoice_template_versions (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoices ADD CONSTRAINT fk_tenant_invoices_approval_instance_id_498e6a49 FOREIGN KEY (tenant_id, approval_instance_id) REFERENCES public.approval_instances (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoices ADD CONSTRAINT fk_tenant_invoices_company_id_1785d54b FOREIGN KEY (tenant_id, company_id) REFERENCES public.companies (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoices ADD CONSTRAINT fk_tenant_invoices_customer_id_0ee9eee7 FOREIGN KEY (tenant_id, customer_id) REFERENCES public.customers (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoices ADD CONSTRAINT fk_tenant_invoices_finalized_by_0b74563b FOREIGN KEY (tenant_id, finalized_by) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoices ADD CONSTRAINT fk_tenant_invoices_invoice_profile_id_db6e76bd FOREIGN KEY (tenant_id, invoice_profile_id) REFERENCES public.invoice_profiles (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoices ADD CONSTRAINT fk_tenant_invoices_source_preview_id_60ce70cc FOREIGN KEY (tenant_id, source_preview_id) REFERENCES public.invoice_previews (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoices ADD CONSTRAINT fk_tenant_invoices_template_id_b218d0e2 FOREIGN KEY (tenant_id, template_id) REFERENCES public.invoice_templates (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.invoices ADD CONSTRAINT fk_tenant_invoices_template_version_id_2d64455a FOREIGN KEY (tenant_id, template_version_id) REFERENCES public.invoice_template_versions (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.librenms_bill_mappings ADD CONSTRAINT fk_tenant_librenms_bill_mappings_company_id_12912e32 FOREIGN KEY (tenant_id, company_id) REFERENCES public.companies (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.librenms_bill_mappings ADD CONSTRAINT fk_tenant_librenms_bill_mappings_contract_item_id_5bce7c27 FOREIGN KEY (tenant_id, contract_item_id) REFERENCES public.contract_items (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.librenms_bill_mappings ADD CONSTRAINT fk_tenant_librenms_bill_mappings_customer_id_6c4254ed FOREIGN KEY (tenant_id, customer_id) REFERENCES public.customers (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.librenms_bill_mappings ADD CONSTRAINT fk_tenant_librenms_bill_mappings_librenms_instance_id_d5df3c37 FOREIGN KEY (tenant_id, librenms_instance_id) REFERENCES public.librenms_instances (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.librenms_bill_mappings ADD CONSTRAINT fk_tenant_librenms_bill_mappings_service_id_b2b57ec0 FOREIGN KEY (tenant_id, service_id) REFERENCES public.services (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.librenms_discovered_bills ADD CONSTRAINT fk_tenant_librenms_discovered_bills_librenms_instance__76711c34 FOREIGN KEY (tenant_id, librenms_instance_id) REFERENCES public.librenms_instances (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.notification_logs ADD CONSTRAINT fk_tenant_notification_logs_invoice_id_67126051 FOREIGN KEY (tenant_id, invoice_id) REFERENCES public.invoices (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.notification_logs ADD CONSTRAINT fk_tenant_notification_logs_notification_template_id_ca7cc0aa FOREIGN KEY (tenant_id, notification_template_id) REFERENCES public.notification_templates (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.notification_logs ADD CONSTRAINT fk_tenant_notification_logs_payment_id_03b19660 FOREIGN KEY (tenant_id, payment_id) REFERENCES public.payments (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.notification_templates ADD CONSTRAINT fk_tenant_notification_templates_created_by_3a37b950 FOREIGN KEY (tenant_id, created_by) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.payment_allocations ADD CONSTRAINT fk_tenant_payment_allocations_allocated_by_c617ebbd FOREIGN KEY (tenant_id, allocated_by) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.payment_allocations ADD CONSTRAINT fk_tenant_payment_allocations_invoice_id_688e6697 FOREIGN KEY (tenant_id, invoice_id) REFERENCES public.invoices (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.payment_allocations ADD CONSTRAINT fk_tenant_payment_allocations_payment_id_5c895c99 FOREIGN KEY (tenant_id, payment_id) REFERENCES public.payments (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.payment_allocations ADD CONSTRAINT fk_tenant_payment_allocations_reversed_by_00fe02fa FOREIGN KEY (tenant_id, reversed_by) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.payment_refunds ADD CONSTRAINT fk_tenant_payment_refunds_created_by_566bc371 FOREIGN KEY (tenant_id, created_by) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.payment_refunds ADD CONSTRAINT fk_tenant_payment_refunds_payment_id_cda9146d FOREIGN KEY (tenant_id, payment_id) REFERENCES public.payments (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.payments ADD CONSTRAINT fk_tenant_payments_attachment_file_id_9f8ed99d FOREIGN KEY (tenant_id, attachment_file_id) REFERENCES public.files (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.payments ADD CONSTRAINT fk_tenant_payments_company_id_e05306e5 FOREIGN KEY (tenant_id, company_id) REFERENCES public.companies (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.payments ADD CONSTRAINT fk_tenant_payments_created_by_427a3aed FOREIGN KEY (tenant_id, created_by) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.payments ADD CONSTRAINT fk_tenant_payments_customer_id_a5b25e27 FOREIGN KEY (tenant_id, customer_id) REFERENCES public.customers (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.pricing_rule_versions ADD CONSTRAINT fk_tenant_pricing_rule_versions_created_by_b2e4eb83 FOREIGN KEY (tenant_id, created_by) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.pricing_rule_versions ADD CONSTRAINT fk_tenant_pricing_rule_versions_pricing_rule_id_78719438 FOREIGN KEY (tenant_id, pricing_rule_id) REFERENCES public.pricing_rules (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.pricing_tiers ADD CONSTRAINT fk_tenant_pricing_tiers_pricing_rule_version_id_31ecd403 FOREIGN KEY (tenant_id, pricing_rule_version_id) REFERENCES public.pricing_rule_versions (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE public.role_permissions ADD CONSTRAINT fk_tenant_role_permissions_role_id_700767f1 FOREIGN KEY (tenant_id, role_id) REFERENCES public.roles (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE public.service_resources ADD CONSTRAINT fk_tenant_service_resources_service_id_14373646 FOREIGN KEY (tenant_id, service_id) REFERENCES public.services (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.services ADD CONSTRAINT fk_tenant_services_company_id_d59a3998 FOREIGN KEY (tenant_id, company_id) REFERENCES public.companies (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.services ADD CONSTRAINT fk_tenant_services_customer_id_1ca1c661 FOREIGN KEY (tenant_id, customer_id) REFERENCES public.customers (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.services ADD CONSTRAINT fk_tenant_services_product_id_cbc1f630 FOREIGN KEY (tenant_id, product_id) REFERENCES public.products (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.services ADD CONSTRAINT fk_tenant_services_service_group_id_cec92421 FOREIGN KEY (tenant_id, service_group_id) REFERENCES public.service_groups (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.template_bindings ADD CONSTRAINT fk_tenant_template_bindings_template_id_e625a15d FOREIGN KEY (tenant_id, template_id) REFERENCES public.invoice_templates (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.usage_current ADD CONSTRAINT fk_tenant_usage_current_mapping_id_20677f27 FOREIGN KEY (tenant_id, mapping_id) REFERENCES public.librenms_bill_mappings (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.usage_snapshot_files ADD CONSTRAINT fk_tenant_usage_snapshot_files_file_id_592f31b6 FOREIGN KEY (tenant_id, file_id) REFERENCES public.files (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.usage_snapshot_files ADD CONSTRAINT fk_tenant_usage_snapshot_files_usage_snapshot_id_fee4d859 FOREIGN KEY (tenant_id, usage_snapshot_id) REFERENCES public.usage_snapshots (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.usage_snapshots ADD CONSTRAINT fk_tenant_usage_snapshots_contract_item_id_10a1d52b FOREIGN KEY (tenant_id, contract_item_id) REFERENCES public.contract_items (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.usage_snapshots ADD CONSTRAINT fk_tenant_usage_snapshots_created_by_d1efb1da FOREIGN KEY (tenant_id, created_by) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.usage_snapshots ADD CONSTRAINT fk_tenant_usage_snapshots_librenms_instance_id_d1849994 FOREIGN KEY (tenant_id, librenms_instance_id) REFERENCES public.librenms_instances (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.usage_snapshots ADD CONSTRAINT fk_tenant_usage_snapshots_mapping_id_b4a8515b FOREIGN KEY (tenant_id, mapping_id) REFERENCES public.librenms_bill_mappings (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.usage_sync_runs ADD CONSTRAINT fk_tenant_usage_sync_runs_job_id_7ac31331 FOREIGN KEY (tenant_id, job_id) REFERENCES public.background_jobs (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE SET NULL (job_id) NOT VALID;
ALTER TABLE public.usage_sync_runs ADD CONSTRAINT fk_tenant_usage_sync_runs_librenms_instance_id_1e62cefe FOREIGN KEY (tenant_id, librenms_instance_id) REFERENCES public.librenms_instances (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.usage_sync_runs ADD CONSTRAINT fk_tenant_usage_sync_runs_mapping_id_832df8b8 FOREIGN KEY (tenant_id, mapping_id) REFERENCES public.librenms_bill_mappings (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.user_roles ADD CONSTRAINT fk_tenant_user_roles_assigned_by_6e8baa7b FOREIGN KEY (tenant_id, assigned_by) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE public.user_roles ADD CONSTRAINT fk_tenant_user_roles_role_id_d117ee60 FOREIGN KEY (tenant_id, role_id) REFERENCES public.roles (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE public.user_roles ADD CONSTRAINT fk_tenant_user_roles_user_id_d369ae1b FOREIGN KEY (tenant_id, user_id) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;
ALTER TABLE public.user_sessions ADD CONSTRAINT fk_tenant_user_sessions_user_id_3921b3f3 FOREIGN KEY (tenant_id, user_id) REFERENCES public.users (tenant_id, id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE NOT VALID;

-- IP buckets are global. Identity buckets may be unresolved, but a stored user must
-- always carry its tenant; MFA user buckets always carry both identifiers.
ALTER TABLE public.authentication_rate_limits ADD CONSTRAINT ck_authentication_rate_limits_identity_scope CHECK ((bucket_type IN ('LOGIN_IP', 'MFA_IP') AND tenant_id IS NULL AND user_id IS NULL) OR (bucket_type = 'LOGIN_IDENTITY' AND (user_id IS NULL OR tenant_id IS NOT NULL)) OR (bucket_type = 'MFA_USER' AND tenant_id IS NOT NULL AND user_id IS NOT NULL)) NOT VALID;

ALTER TABLE public.approval_actions VALIDATE CONSTRAINT fk_tenant_approval_actions_actor_id_247cb391;
ALTER TABLE public.approval_actions VALIDATE CONSTRAINT fk_tenant_approval_actions_approval_instance_id_d3d74081;
ALTER TABLE public.approval_actions VALIDATE CONSTRAINT fk_tenant_approval_actions_approval_step_id_af3f2ef9;
ALTER TABLE public.approval_instances VALIDATE CONSTRAINT fk_tenant_approval_instances_invoice_preview_id_c67e379f;
ALTER TABLE public.approval_instances VALIDATE CONSTRAINT fk_tenant_approval_instances_requested_by_56e54503;
ALTER TABLE public.approval_instances VALIDATE CONSTRAINT fk_tenant_approval_instances_workflow_version_id_b766650d;
ALTER TABLE public.approval_steps VALIDATE CONSTRAINT fk_tenant_approval_steps_workflow_version_id_cf81c29e;
ALTER TABLE public.approval_workflow_versions VALIDATE CONSTRAINT fk_tenant_approval_workflow_versions_workflow_id_0312ce11;
ALTER TABLE public.approval_workflows VALIDATE CONSTRAINT fk_tenant_approval_workflows_current_version_id_e2aac714;
ALTER TABLE public.audit_chain_heads VALIDATE CONSTRAINT fk_tenant_audit_chain_heads_last_event_id_5c579e7f;
ALTER TABLE public.companies VALIDATE CONSTRAINT fk_tenant_companies_customer_id_9e5312ed;
ALTER TABLE public.contract_files VALIDATE CONSTRAINT fk_tenant_contract_files_contract_id_3d7ffacf;
ALTER TABLE public.contract_files VALIDATE CONSTRAINT fk_tenant_contract_files_file_id_7cacf98c;
ALTER TABLE public.contract_items VALIDATE CONSTRAINT fk_tenant_contract_items_contract_id_ad98988d;
ALTER TABLE public.contract_items VALIDATE CONSTRAINT fk_tenant_contract_items_pricing_rule_id_ad53cf11;
ALTER TABLE public.contract_items VALIDATE CONSTRAINT fk_tenant_contract_items_service_id_1bf23236;
ALTER TABLE public.contracts VALIDATE CONSTRAINT fk_tenant_contracts_company_id_91d4c6d7;
ALTER TABLE public.contracts VALIDATE CONSTRAINT fk_tenant_contracts_customer_id_1ba6505c;
ALTER TABLE public.customer_contacts VALIDATE CONSTRAINT fk_tenant_customer_contacts_company_id_983f931e;
ALTER TABLE public.customer_contacts VALIDATE CONSTRAINT fk_tenant_customer_contacts_customer_id_7563f8b9;
ALTER TABLE public.customers VALIDATE CONSTRAINT fk_tenant_customers_owner_user_id_f3da1a0a;
ALTER TABLE public.external_identities VALIDATE CONSTRAINT fk_tenant_external_identities_user_id_57b7f6fe;
ALTER TABLE public.files VALIDATE CONSTRAINT fk_tenant_files_created_by_5c3d5d16;
ALTER TABLE public.import_jobs VALIDATE CONSTRAINT fk_tenant_import_jobs_error_file_id_2bee57bb;
ALTER TABLE public.import_jobs VALIDATE CONSTRAINT fk_tenant_import_jobs_requested_by_025de0b8;
ALTER TABLE public.import_jobs VALIDATE CONSTRAINT fk_tenant_import_jobs_source_file_id_3706261e;
ALTER TABLE public.import_row_errors VALIDATE CONSTRAINT fk_tenant_import_row_errors_import_job_id_58330d3b;
ALTER TABLE public.import_staging_rows VALIDATE CONSTRAINT fk_tenant_import_staging_rows_import_job_id_fb9813f4;
ALTER TABLE public.invoice_adjustments VALIDATE CONSTRAINT fk_tenant_invoice_adjustments_attachment_file_id_0a9e92ba;
ALTER TABLE public.invoice_adjustments VALIDATE CONSTRAINT fk_tenant_invoice_adjustments_invoice_id_d63c840c;
ALTER TABLE public.invoice_adjustments VALIDATE CONSTRAINT fk_tenant_invoice_adjustments_source_preview_adjustmen_89088b53;
ALTER TABLE public.invoice_batches VALIDATE CONSTRAINT fk_tenant_invoice_batches_requested_by_034ef5da;
ALTER TABLE public.invoice_files VALIDATE CONSTRAINT fk_tenant_invoice_files_file_id_338c21b8;
ALTER TABLE public.invoice_files VALIDATE CONSTRAINT fk_tenant_invoice_files_invoice_id_2aacc0d6;
ALTER TABLE public.invoice_files VALIDATE CONSTRAINT fk_tenant_invoice_files_template_version_id_a48b662c;
ALTER TABLE public.invoice_items VALIDATE CONSTRAINT fk_tenant_invoice_items_contract_item_id_9a22d010;
ALTER TABLE public.invoice_items VALIDATE CONSTRAINT fk_tenant_invoice_items_invoice_id_277b6765;
ALTER TABLE public.invoice_items VALIDATE CONSTRAINT fk_tenant_invoice_items_pricing_rule_version_id_8f8b4fc5;
ALTER TABLE public.invoice_items VALIDATE CONSTRAINT fk_tenant_invoice_items_service_id_8f2ee3f4;
ALTER TABLE public.invoice_items VALIDATE CONSTRAINT fk_tenant_invoice_items_source_preview_item_id_fb1c78e0;
ALTER TABLE public.invoice_items VALIDATE CONSTRAINT fk_tenant_invoice_items_usage_snapshot_id_76f9df7b;
ALTER TABLE public.invoice_preview_adjustments VALIDATE CONSTRAINT fk_tenant_invoice_preview_adjustments_approved_by_b43bbb20;
ALTER TABLE public.invoice_preview_adjustments VALIDATE CONSTRAINT fk_tenant_invoice_preview_adjustments_attachment_file__611d244c;
ALTER TABLE public.invoice_preview_adjustments VALIDATE CONSTRAINT fk_tenant_invoice_preview_adjustments_created_by_93dd0d68;
ALTER TABLE public.invoice_preview_adjustments VALIDATE CONSTRAINT fk_tenant_invoice_preview_adjustments_invoice_preview__73a94f3f;
ALTER TABLE public.invoice_preview_exclusions VALIDATE CONSTRAINT fk_tenant_invoice_preview_exclusions_created_by_da127772;
ALTER TABLE public.invoice_preview_exclusions VALIDATE CONSTRAINT fk_tenant_invoice_preview_exclusions_invoice_preview_i_20199df2;
ALTER TABLE public.invoice_preview_exclusions VALIDATE CONSTRAINT fk_tenant_invoice_preview_exclusions_invoice_preview_i_7771e7a1;
ALTER TABLE public.invoice_preview_items VALIDATE CONSTRAINT fk_tenant_invoice_preview_items_contract_item_id_2808cd28;
ALTER TABLE public.invoice_preview_items VALIDATE CONSTRAINT fk_tenant_invoice_preview_items_invoice_preview_id_7006776e;
ALTER TABLE public.invoice_preview_items VALIDATE CONSTRAINT fk_tenant_invoice_preview_items_pricing_rule_version_i_1bbddf75;
ALTER TABLE public.invoice_preview_items VALIDATE CONSTRAINT fk_tenant_invoice_preview_items_service_id_3ad55b36;
ALTER TABLE public.invoice_preview_items VALIDATE CONSTRAINT fk_tenant_invoice_preview_items_usage_snapshot_id_2af767d8;
ALTER TABLE public.invoice_previews VALIDATE CONSTRAINT fk_tenant_invoice_previews_approval_workflow_version_i_1262b32d;
ALTER TABLE public.invoice_previews VALIDATE CONSTRAINT fk_tenant_invoice_previews_company_id_58aa4e25;
ALTER TABLE public.invoice_previews VALIDATE CONSTRAINT fk_tenant_invoice_previews_created_by_7815633d;
ALTER TABLE public.invoice_previews VALIDATE CONSTRAINT fk_tenant_invoice_previews_customer_id_26a2e87d;
ALTER TABLE public.invoice_previews VALIDATE CONSTRAINT fk_tenant_invoice_previews_invoice_batch_id_81c7dec3;
ALTER TABLE public.invoice_previews VALIDATE CONSTRAINT fk_tenant_invoice_previews_invoice_profile_id_472cbd97;
ALTER TABLE public.invoice_previews VALIDATE CONSTRAINT fk_tenant_invoice_previews_origin_invoice_id_f30e6c82;
ALTER TABLE public.invoice_previews VALIDATE CONSTRAINT fk_tenant_invoice_previews_template_id_832a142b;
ALTER TABLE public.invoice_previews VALIDATE CONSTRAINT fk_tenant_invoice_previews_template_version_id_6dfb617a;
ALTER TABLE public.invoice_profile_assignments VALIDATE CONSTRAINT fk_tenant_invoice_profile_assignments_contract_item_id_e9d3fed3;
ALTER TABLE public.invoice_profile_assignments VALIDATE CONSTRAINT fk_tenant_invoice_profile_assignments_created_by_a265c49b;
ALTER TABLE public.invoice_profile_assignments VALIDATE CONSTRAINT fk_tenant_invoice_profile_assignments_invoice_profile__d774c0cc;
ALTER TABLE public.invoice_profiles VALIDATE CONSTRAINT fk_tenant_invoice_profiles_approval_workflow_id_a785c673;
ALTER TABLE public.invoice_profiles VALIDATE CONSTRAINT fk_tenant_invoice_profiles_company_id_1664b69e;
ALTER TABLE public.invoice_profiles VALIDATE CONSTRAINT fk_tenant_invoice_profiles_customer_id_1e6e0076;
ALTER TABLE public.invoice_profiles VALIDATE CONSTRAINT fk_tenant_invoice_profiles_template_id_65d1e301;
ALTER TABLE public.invoice_relations VALIDATE CONSTRAINT fk_tenant_invoice_relations_created_by_fed95abb;
ALTER TABLE public.invoice_relations VALIDATE CONSTRAINT fk_tenant_invoice_relations_source_invoice_id_ac9fcb77;
ALTER TABLE public.invoice_relations VALIDATE CONSTRAINT fk_tenant_invoice_relations_target_invoice_id_499eccc5;
ALTER TABLE public.invoice_template_assets VALIDATE CONSTRAINT fk_tenant_invoice_template_assets_file_id_f35d954a;
ALTER TABLE public.invoice_template_assets VALIDATE CONSTRAINT fk_tenant_invoice_template_assets_template_version_id_0699ef21;
ALTER TABLE public.invoice_template_versions VALIDATE CONSTRAINT fk_tenant_invoice_template_versions_created_by_308fd4fb;
ALTER TABLE public.invoice_template_versions VALIDATE CONSTRAINT fk_tenant_invoice_template_versions_template_id_b3ca52de;
ALTER TABLE public.invoice_templates VALIDATE CONSTRAINT fk_tenant_invoice_templates_created_by_4fc9627c;
ALTER TABLE public.invoice_templates VALIDATE CONSTRAINT fk_tenant_invoice_templates_current_version_id_1055498f;
ALTER TABLE public.invoices VALIDATE CONSTRAINT fk_tenant_invoices_approval_instance_id_498e6a49;
ALTER TABLE public.invoices VALIDATE CONSTRAINT fk_tenant_invoices_company_id_1785d54b;
ALTER TABLE public.invoices VALIDATE CONSTRAINT fk_tenant_invoices_customer_id_0ee9eee7;
ALTER TABLE public.invoices VALIDATE CONSTRAINT fk_tenant_invoices_finalized_by_0b74563b;
ALTER TABLE public.invoices VALIDATE CONSTRAINT fk_tenant_invoices_invoice_profile_id_db6e76bd;
ALTER TABLE public.invoices VALIDATE CONSTRAINT fk_tenant_invoices_source_preview_id_60ce70cc;
ALTER TABLE public.invoices VALIDATE CONSTRAINT fk_tenant_invoices_template_id_b218d0e2;
ALTER TABLE public.invoices VALIDATE CONSTRAINT fk_tenant_invoices_template_version_id_2d64455a;
ALTER TABLE public.librenms_bill_mappings VALIDATE CONSTRAINT fk_tenant_librenms_bill_mappings_company_id_12912e32;
ALTER TABLE public.librenms_bill_mappings VALIDATE CONSTRAINT fk_tenant_librenms_bill_mappings_contract_item_id_5bce7c27;
ALTER TABLE public.librenms_bill_mappings VALIDATE CONSTRAINT fk_tenant_librenms_bill_mappings_customer_id_6c4254ed;
ALTER TABLE public.librenms_bill_mappings VALIDATE CONSTRAINT fk_tenant_librenms_bill_mappings_librenms_instance_id_d5df3c37;
ALTER TABLE public.librenms_bill_mappings VALIDATE CONSTRAINT fk_tenant_librenms_bill_mappings_service_id_b2b57ec0;
ALTER TABLE public.librenms_discovered_bills VALIDATE CONSTRAINT fk_tenant_librenms_discovered_bills_librenms_instance__76711c34;
ALTER TABLE public.notification_logs VALIDATE CONSTRAINT fk_tenant_notification_logs_invoice_id_67126051;
ALTER TABLE public.notification_logs VALIDATE CONSTRAINT fk_tenant_notification_logs_notification_template_id_ca7cc0aa;
ALTER TABLE public.notification_logs VALIDATE CONSTRAINT fk_tenant_notification_logs_payment_id_03b19660;
ALTER TABLE public.notification_templates VALIDATE CONSTRAINT fk_tenant_notification_templates_created_by_3a37b950;
ALTER TABLE public.payment_allocations VALIDATE CONSTRAINT fk_tenant_payment_allocations_allocated_by_c617ebbd;
ALTER TABLE public.payment_allocations VALIDATE CONSTRAINT fk_tenant_payment_allocations_invoice_id_688e6697;
ALTER TABLE public.payment_allocations VALIDATE CONSTRAINT fk_tenant_payment_allocations_payment_id_5c895c99;
ALTER TABLE public.payment_allocations VALIDATE CONSTRAINT fk_tenant_payment_allocations_reversed_by_00fe02fa;
ALTER TABLE public.payment_refunds VALIDATE CONSTRAINT fk_tenant_payment_refunds_created_by_566bc371;
ALTER TABLE public.payment_refunds VALIDATE CONSTRAINT fk_tenant_payment_refunds_payment_id_cda9146d;
ALTER TABLE public.payments VALIDATE CONSTRAINT fk_tenant_payments_attachment_file_id_9f8ed99d;
ALTER TABLE public.payments VALIDATE CONSTRAINT fk_tenant_payments_company_id_e05306e5;
ALTER TABLE public.payments VALIDATE CONSTRAINT fk_tenant_payments_created_by_427a3aed;
ALTER TABLE public.payments VALIDATE CONSTRAINT fk_tenant_payments_customer_id_a5b25e27;
ALTER TABLE public.pricing_rule_versions VALIDATE CONSTRAINT fk_tenant_pricing_rule_versions_created_by_b2e4eb83;
ALTER TABLE public.pricing_rule_versions VALIDATE CONSTRAINT fk_tenant_pricing_rule_versions_pricing_rule_id_78719438;
ALTER TABLE public.pricing_tiers VALIDATE CONSTRAINT fk_tenant_pricing_tiers_pricing_rule_version_id_31ecd403;
ALTER TABLE public.role_permissions VALIDATE CONSTRAINT fk_tenant_role_permissions_role_id_700767f1;
ALTER TABLE public.service_resources VALIDATE CONSTRAINT fk_tenant_service_resources_service_id_14373646;
ALTER TABLE public.services VALIDATE CONSTRAINT fk_tenant_services_company_id_d59a3998;
ALTER TABLE public.services VALIDATE CONSTRAINT fk_tenant_services_customer_id_1ca1c661;
ALTER TABLE public.services VALIDATE CONSTRAINT fk_tenant_services_product_id_cbc1f630;
ALTER TABLE public.services VALIDATE CONSTRAINT fk_tenant_services_service_group_id_cec92421;
ALTER TABLE public.template_bindings VALIDATE CONSTRAINT fk_tenant_template_bindings_template_id_e625a15d;
ALTER TABLE public.usage_current VALIDATE CONSTRAINT fk_tenant_usage_current_mapping_id_20677f27;
ALTER TABLE public.usage_snapshot_files VALIDATE CONSTRAINT fk_tenant_usage_snapshot_files_file_id_592f31b6;
ALTER TABLE public.usage_snapshot_files VALIDATE CONSTRAINT fk_tenant_usage_snapshot_files_usage_snapshot_id_fee4d859;
ALTER TABLE public.usage_snapshots VALIDATE CONSTRAINT fk_tenant_usage_snapshots_contract_item_id_10a1d52b;
ALTER TABLE public.usage_snapshots VALIDATE CONSTRAINT fk_tenant_usage_snapshots_created_by_d1efb1da;
ALTER TABLE public.usage_snapshots VALIDATE CONSTRAINT fk_tenant_usage_snapshots_librenms_instance_id_d1849994;
ALTER TABLE public.usage_snapshots VALIDATE CONSTRAINT fk_tenant_usage_snapshots_mapping_id_b4a8515b;
ALTER TABLE public.usage_sync_runs VALIDATE CONSTRAINT fk_tenant_usage_sync_runs_job_id_7ac31331;
ALTER TABLE public.usage_sync_runs VALIDATE CONSTRAINT fk_tenant_usage_sync_runs_librenms_instance_id_1e62cefe;
ALTER TABLE public.usage_sync_runs VALIDATE CONSTRAINT fk_tenant_usage_sync_runs_mapping_id_832df8b8;
ALTER TABLE public.user_roles VALIDATE CONSTRAINT fk_tenant_user_roles_assigned_by_6e8baa7b;
ALTER TABLE public.user_roles VALIDATE CONSTRAINT fk_tenant_user_roles_role_id_d117ee60;
ALTER TABLE public.user_roles VALIDATE CONSTRAINT fk_tenant_user_roles_user_id_d369ae1b;
ALTER TABLE public.user_sessions VALIDATE CONSTRAINT fk_tenant_user_sessions_user_id_3921b3f3;
ALTER TABLE public.authentication_rate_limits VALIDATE CONSTRAINT ck_authentication_rate_limits_identity_scope;

