
-- IDs are generated by the application as UUIDv7.

CREATE TABLE tenants (
    id uuid PRIMARY KEY,
    tenant_code varchar(64) NOT NULL UNIQUE,
    tenant_name varchar(200) NOT NULL,
    default_timezone varchar(64) NOT NULL DEFAULT 'Asia/Shanghai',
    default_currency char(3) NOT NULL DEFAULT 'CNY',
    status varchar(24) NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CLOSED')),
    settings_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    version bigint NOT NULL DEFAULT 0
);

CREATE TABLE currencies (
    code char(3) PRIMARY KEY,
    display_name varchar(100) NOT NULL,
    symbol varchar(16),
    minor_unit smallint NOT NULL CHECK (minor_unit BETWEEN 0 AND 6),
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO currencies(code, display_name, symbol, minor_unit) VALUES
('CNY', 'Chinese Yuan', '¥', 2),
('USD', 'US Dollar', '$', 2),
('HKD', 'Hong Kong Dollar', 'HK$', 2),
('JPY', 'Japanese Yen', '¥', 0)
ON CONFLICT (code) DO NOTHING;

ALTER TABLE tenants
    ADD CONSTRAINT fk_tenants_default_currency
    FOREIGN KEY (default_currency) REFERENCES currencies(code);

CREATE TABLE users (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id),
    username varchar(100) NOT NULL,
    email varchar(320) NOT NULL,
    display_name varchar(160) NOT NULL,
    password_hash varchar(512),
    mfa_enabled boolean NOT NULL DEFAULT false,
    mfa_secret_ciphertext text,
    status varchar(24) NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('INVITED', 'ACTIVE', 'LOCKED', 'DISABLED')),
    last_login_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    version bigint NOT NULL DEFAULT 0,
    UNIQUE (tenant_id, username),
    UNIQUE (tenant_id, email)
);

CREATE TABLE external_identities (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id),
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider_code varchar(64) NOT NULL,
    subject varchar(320) NOT NULL,
    claims_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, provider_code, subject)
);

CREATE TABLE roles (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id),
    role_code varchar(100) NOT NULL,
    role_name varchar(160) NOT NULL,
    system_role boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, role_code)
);

CREATE TABLE permissions (
    permission_code varchar(160) PRIMARY KEY,
    description varchar(500) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE role_permissions (
    tenant_id uuid NOT NULL REFERENCES tenants(id),
    role_id uuid NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_code varchar(160) NOT NULL REFERENCES permissions(permission_code),
    PRIMARY KEY (tenant_id, role_id, permission_code)
);

CREATE TABLE user_roles (
    tenant_id uuid NOT NULL REFERENCES tenants(id),
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id uuid NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    assigned_by uuid REFERENCES users(id),
    assigned_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, user_id, role_id)
);

CREATE TABLE user_sessions (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id),
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash varchar(128) NOT NULL UNIQUE,
    ip_address inet,
    user_agent varchar(1000),
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_user_sessions_active
    ON user_sessions(user_id, expires_at) WHERE revoked_at IS NULL;

CREATE TABLE files (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id),
    storage_provider varchar(24) NOT NULL
        CHECK (storage_provider IN ('MINIO', 'S3', 'LOCAL')),
    bucket_name varchar(160) NOT NULL,
    object_key varchar(1024) NOT NULL,
    original_filename varchar(512) NOT NULL,
    mime_type varchar(255) NOT NULL,
    file_size bigint NOT NULL CHECK (file_size >= 0),
    sha256 char(64) NOT NULL,
    encryption_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_by uuid REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    UNIQUE (tenant_id, bucket_name, object_key)
);

CREATE INDEX idx_files_sha256 ON files(tenant_id, sha256);

